<?php return array (
  'en_gram' => '',
  'en_lm' => '',
  'lv_gram' => '',
  'lv_lm' => '',
  'de_gram' => '',
  'de_lm' => '',
  'fr_gram' => '',
  'fr_lm' => '',
  'google_key' => '',
  'yandex_key' => '',
  'bing_id' => '',
  'bing_se' => '',
  'hugo_pw' => '',
  'hugo_em' => '',
) ;